config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    member do
      get :add_email
      patch :signup_email
    end
  end

  concern :ratingable do
    member do
      post :vote_up
      post :vote_down
      post :vote_reset
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :search, only: :index

  resources :attachments, only: :destroy
  resources :questions, except: [:edit], concerns: [:ratingable, :commentable] do
    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:ratingable, :commentable] do
      member do
        patch :select_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Ratingable
  include Commentable
  include Subscribable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable

  belongs_to :user

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: :show

  authorize_resource

  def index
    respond_with(Question.all)
  end

  def show
    respond_with(@question, serializer: QuestionShowSerializer)
  end

  def create
    @question = current_user.questions.create(question_params)
    respond_with(@question)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Ratinged

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show]
  before_action :find_current_user_question, only: [:destroy, :update]
  before_action :build_answer, only: :show

  after_action :publish_question, only: :create

  authorize_resource

  respond_to :js, :html

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = current_user.questions.build)
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def destroy
    respond_with(@question.destroy)
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  private

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def find_question
    @question = Question.find(params[:id])
    @answers = @question.answers.by_best
  end

  def find_current_user_question
    @question = current_user.questions.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions', question: @question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
- cache question do
  .question_errors
  div class="question question_#{question.id}" data-id="#{question.id}"
    p
      h2 = question.title
    p
      h3 = question.body
    p= render 'shared/rating', resource: question
    p= link_to 'Show', question
    - if can?(:create, Subscription)
      - if question.subscribed?(current_user)
        p= link_to subscription_path(question.subscribed?(current_user)), method: :delete do
          | Unsubscribe
      - else
        p= link_to question_subscriptions_path(question), method: :post do
          | Subscribe
    p Attachments:
    ul
      - question.attachments.each do |a|
        - cache a do
          li id="attachment_#{a.id}"
            = link_to a.file.identifier, a.file.url
            - if current_user&.author_of?(question)
              = link_to 'Remove file', attachment_path(a), method: :delete, data: { confirm: 'are you sure?', remote: true }
    - if current_user&.author_of?(question)
      p= link_to 'Edit', '', class: 'edit-question-link', data: {question_id: question.id}
      p= link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are you sure?' }
      div id="edit-question-form#{question.id}" class="edit-question-form"
        = form_with model: question do |f|
          = f.label :title
          = f.text_field :title

          = f.label :body
          = f.text_area :body
          = f.submit 'Save'
    h4 Comments
    div class="comment_#{question.class}_#{question.id}"
      p
        = render question.comments
      p
        = render 'comments/form', resource: question

app/views/questions/index.html.slim
h2 All questions
= link_to 'Ask question', new_question_path
table
  thead
    tr
      th Question
      th
  tbody
    = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  #attachments
    = f.fields_for :attachments, @question.attachments.build do |attachment|
      = render 'shared/attachment_fields', f: attachment

      = link_to_add_association 'Add attachment', f, :attachments, partial: 'shared/attachment_fields'
  = f.submit

app/views/questions/show.html.slim
.notice

= render @question

h2 Answers
.answers
  - if @answers.present?
    =render @answers
  - else
    h4 No answers yet

#answer_errors

= form_with model: [@question, @answer], class: 'new_answer_form' do |form|
  = form.label :body
  = form.text_area :body
  #attachments
    = form.fields_for :attachments, @answer.attachments.build do |attachment|
      = render 'shared/attachment_fields', f: attachment

      = link_to_add_association 'Add attachment', form, :attachments, partial: 'shared/attachment_fields'
  = form.submit

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('#question_errors').html('<%= j render "shared/errors", resource: @question %>');
<% else %>
  $('.question_<%= @question.id %>').replaceWith('<%= j render @question %>');
<% end %>